### ISSUE TITLE
Can I have this package name?

### ISSUE THREAD

**Issue by sebmck** [jquense/babel-plugin-external-helpers#1]
Right now the plugin that replaces the previous option is called [`babel-plugin-external-helpers-2`](https://github.com/babel/babel/tree/master/packages/babel-plugin-external-helpers-2). Would you be willing to give up the name and change this plugin to something else? It's not immediately clear to me how this plugin relates to external helpers in the first place.

Thanks!

**Comment by jquense** [comment]
Sure, no problem. it's only used on some personal projects anyway (it's used with the old external helpers option for a minimal runtime like tranaform). 

I am travelling currently though so I can't quite get to moving this and switching over stuff that depends on it right away. but you are welcome to the name. npm username to transfer to? "sebmck" ?

**Comment by sebmck** [comment]
Yep, npm username is `sebmck`. Thank you so much!

**Comment by jquense** [comment]
OK I switched you to the owner of the npm package. I still haven't had a chance to move this or things depending on it to anything new...please be kind and bump a major version when you publish :P

**Comment by kidwm** [comment]
@sebmck you can now release a new version of `babel-plugin-external-helpers`

**Comment by sebmck** [comment]
@kidwm Thanks for the ping.
@jquense Thank you, much appreciated!
